### ISSUE TITLE
API documentation lacks details to create stub files

### ISSUE THREAD

**Issue by dcelasun** [chobie/php-protocolbuffers#28]
I tried creating a stub (see the predis example [here](https://github.com/wayne530/phpstorm-phpredis-stub/blob/master/redis.php)) file to be used for IDE type hinting / autocomplete but the API documentation is quite rudimentary (missing constants values, method parameters etc.)

Can you either update the API documentation with full class definitions and constant values, or maybe create a stub file as an example?

**Comment by chobie** [comment]
I've added some classes into `protocolbuffers.stub.php`. I'll improve that when I have some time.

In fact, ProtocolBuffers has more classes but those classes doesn't expect call manually.
I plan to add those classes into stub file when I change to beta version.

**Comment by dcelasun** [comment]
Great, thanks!

**Comment by dcelasun** [comment]
@chobie Would you consider the API stable at this point? We are planning on using this extension on a large scale production application and our internal tests seem to be promising. Do you expect any large changes? BC breaks?

**Comment by chobie** [comment]
@dcelasun some API (like extensions, unknown fields) might change.
but basic API (ProtocolBuffersMessage::setXXX, getXXX, appendXXXX...) are stable. 
let me put `@api` annotation for those methods on stub file.

I'm only considering `ProtocolBuffersMessage::parseFromString()` API as other binding implemented as
member method. not static. static method is very easy to use instead of create object and call 
`parseFromString` method. so I prefer static method for static method to member method at this situation.

I also use this extension for our work. I don't break BC unless otherwise my implementation or API design was incorrect.

anyway, current status is still alpha. please feel free to ask me with posting issue or #php-protocolbuffers at freenode.net.

**Comment by dcelasun** [comment]
@chobie Thanks! I'll drop by the IRC channel if anything comes up.
